3.1 Warm Up Exercises:
1. Sorting and Subsetting:
Complete all following Task:
• Dataset for the Task: "titanic.csv"
Following task is common for all the problem:
1. Load the provided dataset and import in pandas DataFrame.
2. Check info of the DataFrame and identify following:

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving Titanic-Dataset.csv to Titanic-Dataset.csv

In [ ]:
import pandas as pd
df=pd.read_csv('Titanic-Dataset.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

Problem 1 - Sorting:
1. Create a DataFrame called fare that contains only the Fare column of the Titanic dataset. Print the
head of the result.

In [ ]:
fare=df["Fare"]
fare.head()

0     7.2500
1    71.2833
2     7.9250
3    53.1000
4     8.0500
Name: Fare, dtype: float64

Create a DataFrame called class age that contains only the Pclass and Age columns of the Titanic
dataset, in that order. Print the head of the result

In [ ]:
class_age=df[["Pclass","Age"]]
class_age.head()

   Pclass   Age
0       3  22.0
1       1  38.0
2       3  26.0
3       1  35.0
4       3  35.0

Create a DataFrame called survived gender that contains the Survived and Sex columns of the
Titanic dataset, in that order.Print the head of the result

In [ ]:
survived_gender=df[["Survived","Sex"]]
survived_gender.head()

   Survived     Sex
0         0    male
1         1  female
2         1  female
3         1  female
4         0    male

Problem - 2 - Subsetting:
Complete all the following Task:
Subsetting Rows:
1. Filter the Titanic dataset for cases where the passenger’s fare is greater than 100, assigning it
to fare gt 100.View the printed result.

In [ ]:
fare_gt_100=df[df["Fare"]>100]
fare_gt_100

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.00,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.00,3,2,19950,263.0000,C23 C25 C27,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.00,0,1,PC 17558,247.5208,B58 B60,C
195,196,1,1,"Lurette, Miss. Elise",female,58.00,0,0,PC 17569,146.5208,B80,C
215,216,1,1,"Newell, Miss. Madeleine",female,31.00,1,0,35273,113.2750,D36,C
258,259,1,1,"Ward, Miss. Anna",female,35.00,0,0,PC 17755,512.3292,NaN,C
268,269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.00,0,1,PC 17582,153.4625,C125,S
269,270,1,1,"Bissette, Miss. Amelia",female,35.00,0,0,PC 17760,135.6333,C99,S
297,298,0,1,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
299,300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.00,0,1,PC 17558,247.5208,B58 B60,C
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
306,307,1,1,"Fleming, Miss. Margaret",female,NaN,0,0,17421,110.8833,NaN,C
307,308,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17.00,1,0,PC 17758,108.9000,C65,C
311,312,1,1,"Ryerson, Miss. Emily Borie",female,18.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
318,319,1,1,"Wick, Miss. Mary Natalie",female,31.00,0,2,36928,164.8667,C7,S
319,320,1,1,"Spedden, Mrs. Frederic Oakley (Margaretta Corn...",female,40.00,1,1,16966,134.5000,E34,C
325,326,1,1,"Young, Miss. Marie Grice",female,36.00,0,0,PC 17760,135.6333,C32,C
332,333,0,1,"Graham, Mr. George Edward",male,38.00,0,1,PC 17582,153.4625,C91,S
334,335,1,1,"Frauenthal, Mrs. Henry William (Clara Heinshei...",female,NaN,1,0,PC 17611,133.6500,NaN,S
337,338,1,1,"Burns, Miss. Elizabeth Margaret",female,41.00,0,0,16966,134.5000,E40,C
341,342,1,1,"Fortune, Miss. Alice Elizabeth",female,24.00,3,2,19950,263.0000,C23 C25 C27,S
373,374,0,1,"Ringhini, Mr. Sante",male,22.00,0,0,PC 17760,135.6333,NaN,C
377,378,0,1,"Widener, Mr. Harry Elkins",male,27.00,0,2,113503,211.5000,C82,C
380,381,1,1,"Bidois, Miss. Rosalie",female,42.00,0,0,PC 17757,227.5250,NaN,C
390,391,1,1,"Carter, Mr. William Ernest",male,36.00,1,2,113760,120.0000,B96 B98,S
393,394,1,1,"Newell, Miss. Marjorie",female,23.00,1,0,35273,113.2750,D36,C
435,436,1,1,"Carter, Miss. Lucile Polk",female,14.00,1,2,113760,120.0000,B96 B98,S
438,439,0,1,"Fortune, Mr. Mark",male,64.00,1,4,19950,263.0000,C23 C25 C27,S
498,499,0,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S
505,506,0,1,"Penasco y Castellana, Mr. Victor de Satode",male,18.00,1,0,PC 17758,108.9000,C65,C
527,528,0,1,"Farthing, Mr. John",male,NaN,0,0,PC 17483,221.7792,C95,S
537,538,1,1,"LeRoy, Miss. Bertha",female,30.00,0,0,PC 17761,106.4250,NaN,C
544,545,0,1,"Douglas, Mr. Walter Donald",male,50.00,1,0,PC 17761,106.4250,C86,C
550,551,1,1,"Thayer, Mr. John Borland Jr",male,17.00,0,2,17421,110.8833,C70,C
557,558,0,1,"Robbins, Mr. Victor",male,NaN,0,0,PC 17757,227.5250,NaN,C
581,582,1,1,"Thayer, Mrs. John Borland (Marian Longstreth M...",female,39.00,1,1,17421,110.8833,C68,C
609,610,1,1,"Shutes, Miss. Elizabeth W",female,40.00,0,0,PC 17582,153.4625,C125,S
659,660,0,1,"Newell, Mr. Arthur Webster",male,58.00,0,2,35273,113.2750,D48,C
660,661,1,1,"Frauenthal, Dr. Henry William",male,50.00,2,0,PC 17611,133.6500,NaN,S
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.00,0,1,PC 17755,512.3292,B51 B53 B55,C
689,690,1,1,"Madill, Miss. Georgette Alexandra",female,15.00,0,1,24160,211.3375,B5,S
698,699,0,1,"Thayer, Mr. John Borland",male,49.00,1,1,17421,110.8833,C68,C
700,701,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.00,1,0,PC 17757,227.5250,C62 C64,C
708,709,1,1,"Cleaver, Miss. Alice",female,22.00,0,0,113781,151.5500,NaN,S
716,717,1,1,"Endres, Miss. Caroline Louise",female,38.00,0,0,PC 17757,227.5250,C45,C
730,731,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.00,0,0,PC 17755,512.3292,B101,C
742,743,1,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
763,764,1,1,"Carter, Mrs. William Ernest (Lucile Polk)",female,36.00,1,2,113760,120.0000,B96 B98,S
779,780,1,1,"Robert, Mrs. Edward Scott (Elisabeth Walton Mc...",female,43.00,0,1,24160,211.3375,B3,S
802,803,1,1,"Carter, Master. William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.00,1,1,36928,164.8667,NaN,S

Filter the Titanic dataset for cases where the passenger’s class (Pclass) is 1, assigning it to
first class.View the printed result.

In [ ]:
first_class=df[df["Pclass"]==1]
first_class

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

 Filter the Titanic dataset for cases where the passenger’s age is less than 18 and the passenger
is female (Sex is "female"), assigning it to female under 18. View the printed result

In [ ]:
female_under_18=df[df["Age"]<18],df[df["Sex"]=="female"]
female_under_18

(     PassengerId  Survived  Pclass                                     Name  \
 7              8         0       3           Palsson, Master. Gosta Leonard
 9             10         1       2      Nasser, Mrs. Nicholas (Adele Achem)
 10            11         1       3          Sandstrom, Miss. Marguerite Rut
 14            15         0       3     Vestrom, Miss. Hulda Amanda Adolfina
 16            17         0       3                     Rice, Master. Eugene
 ..           ...       ...     ...                                      ...
 850          851         0       3  Andersson, Master. Sigvard Harald Elias
 852          853         0       3                  Boulos, Miss. Nourelain
 853          854         1       1                Lines, Miss. Mary Conover
 869          870         1       3          Johnson, Master. Harold Theodor
 875          876         1       3         Najib, Miss. Adele Kiamie "Jane"

         Sex   Age  SibSp  Parch    Ticket     Fare Cabin Embarked
 7      male   2.0      3      1    349909  21.0750   NaN        S
 9    female  14.0      1      0    237736  30.0708   NaN        C
 10   female   4.0      1      1   PP 9549  16.7000    G6        S
 14   female  14.0      0      0    350406   7.8542   NaN        S
 16     male   2.0      4      1    382652  29.1250   NaN        Q
 ..      ...   ...    ...    ...       ...      ...   ...      ...
 850    male   4.0      4      2    347082  31.2750   NaN        S
 852  female   9.0      1      1      2678  15.2458   NaN        C
 853  female  16.0      0      1  PC 17592  39.4000   D28        S
 869    male   4.0      1      1    347742  11.1333   NaN        S
 875  female  15.0      0      0      2667   7.2250   NaN        C

 [113 rows x 12 columns],
      PassengerId  Survived  Pclass  \
 1              2         1       1
 2              3         1       3
 3              4         1       1
 8              9         1       3
 9             10         1       2
 ..           ...       ...     ...
 880          881         1       2
 882          883         0       3
 885          886         0       3
 887          888         1       1
 888          889         0       3

                                                   Name     Sex   Age  SibSp  \
 1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
 2                               Heikkinen, Miss. Laina  female  26.0      0
 3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
 8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
 9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1
 ..                                                 ...     ...   ...    ...
 880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0
 882                       Dahlberg, Miss. Gerda Ulrika  female  22.0      0
 885               Rice, Mrs. William (Margaret Norton)  female  39.0      0
 887                       Graham, Miss. Margaret Edith  female  19.0      0
 888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1

      Parch            Ticket     Fare Cabin Embarked
 1        0          PC 17599  71.2833   C85        C
 2        0  STON/O2. 3101282   7.9250   NaN        S
 3        0            113803  53.1000  C123        S
 8        2            347742  11.1333   NaN        S
 9        0            237736  30.0708   NaN        C
 ..     ...               ...      ...   ...      ...
 880      1            230433  26.0000   NaN        S
 882      0              7552  10.5167   NaN        S
 885      5            382652  29.1250   NaN        Q
 887      0            112053  30.0000   B42        S
 888      2        W./C. 6607  23.4500   NaN        S

 [314 rows x 12 columns])

Subsetting Rows by Categorical variables:
1. Filter the Titanic dataset for passengers whose Embarked port is either "C" (Cherbourg) or "S"
(Southampton), assigning the result to embarked c or s. View the printed result.

In [ ]:
embarked_c_s=df[df["Embarked"]=="C"],df[df["Embarked"]=="S"]
embarked_c_s

(     PassengerId  Survived  Pclass  \
 1              2         1       1
 9             10         1       2
 19            20         1       3
 26            27         0       3
 30            31         0       1
 ..           ...       ...     ...
 866          867         1       2
 874          875         1       2
 875          876         1       3
 879          880         1       1
 889          890         1       1

                                                   Name     Sex   Age  SibSp  \
 1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
 9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1
 19                             Masselmani, Mrs. Fatima  female   NaN      0
 26                             Emir, Mr. Farred Chehab    male   NaN      0
 30                            Uruchurtu, Don. Manuel E    male  40.0      0
 ..                                                 ...     ...   ...    ...
 866                       Duran y More, Miss. Asuncion  female  27.0      1
 874              Abelson, Mrs. Samuel (Hannah Wizosky)  female  28.0      1
 875                   Najib, Miss. Adele Kiamie "Jane"  female  15.0      0
 879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0
 889                              Behr, Mr. Karl Howell    male  26.0      0

      Parch         Ticket     Fare Cabin Embarked
 1        0       PC 17599  71.2833   C85        C
 9        0         237736  30.0708   NaN        C
 19       0           2649   7.2250   NaN        C
 26       0           2631   7.2250   NaN        C
 30       0       PC 17601  27.7208   NaN        C
 ..     ...            ...      ...   ...      ...
 866      0  SC/PARIS 2149  13.8583   NaN        C
 874      0      P/PP 3381  24.0000   NaN        C
 875      0           2667   7.2250   NaN        C
 879      1          11767  83.1583   C50        C
 889      0         111369  30.0000  C148        C

 [168 rows x 12 columns],
      PassengerId  Survived  Pclass  \
 0              1         0       3
 2              3         1       3
 3              4         1       1
 4              5         0       3
 6              7         0       1
 ..           ...       ...     ...
 883          884         0       2
 884          885         0       3
 886          887         0       2
 887          888         1       1
 888          889         0       3

                                              Name     Sex   Age  SibSp  Parch  \
 0                         Braund, Mr. Owen Harris    male  22.0      1      0
 2                          Heikkinen, Miss. Laina  female  26.0      0      0
 3    Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1      0
 4                        Allen, Mr. William Henry    male  35.0      0      0
 6                         McCarthy, Mr. Timothy J    male  54.0      0      0
 ..                                            ...     ...   ...    ...    ...
 883                 Banfield, Mr. Frederick James    male  28.0      0      0
 884                        Sutehall, Mr. Henry Jr    male  25.0      0      0
 886                         Montvila, Rev. Juozas    male  27.0      0      0
 887                  Graham, Miss. Margaret Edith  female  19.0      0      0
 888      Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1      2

                Ticket     Fare Cabin Embarked
 0           A/5 21171   7.2500   NaN        S
 2    STON/O2. 3101282   7.9250   NaN        S
 3              113803  53.1000  C123        S
 4              373450   8.0500   NaN        S
 6               17463  51.8625   E46        S
 ..                ...      ...   ...      ...
 883  C.A./SOTON 34068  10.5000   NaN        S
 884   SOTON/OQ 392076   7.0500   NaN        S
 886            211536  13.0000   NaN        S
 887            112053  30.0000   B42        S
 888        W./C. 6607  23.4500   NaN        S

 [644 rows x 12 columns])

Filter the Titanic dataset for passengers whose Pclass is in the list [1, 2] (indicating first
or second class), assigning the result to first second class.View the printed result.

In [ ]:
first_second_class=df[df["Pclass"].isin([1,2])]
first_second_class

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

3.2 Exploratory Data Analysis Practice Exercise - 1.
Warning: Handle missing values in the Age column by filling them with the median age of
the dataset before performing the division.)
Answer the following questions from Dataset:
Which passenger had the highest fare paid relative to their age?
To answer the question perform following operations:
1. Add a column to the Titanic dataset, fare per year, containing the fare divided by the age of
the passenger(i.e., Fare/Age).
2. Subset rows where fare per year is higher than 5, assigning this to high fare age.
3. Sort high fare age by descending fare per year, assigning this to high fare age srt.
4. Select only the Name and fare per year columns of high fare age srt and save the result as result.
5. Look at the result

In [ ]:
df["Age"].fillna(df["Age"].median(),inplace=True)
df["Fare_per_year"]=df["Fare"]/df["Age"]
high_fare_age=df[df["Fare_per_year"]>5]
high_fare_age_srt=high_fare_age.sort_values(by="Fare_per_year", ascending=False)
result=high_fare_age_srt[["Name","Fare_per_year"]]
result

/tmp/ipython-input-3482215848.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].median(),inplace=True)

                                               Name  Fare_per_year
305                  Allison, Master. Hudson Trevor     164.728261
297                    Allison, Miss. Helen Loraine      75.775000
386                 Goodwin, Master. Sidney Leonard      46.900000
164                    Panula, Master. Eino Viljami      39.687500
183                       Becker, Master. Richard F      39.000000
..                                              ...            ...
348          Coutts, Master. William Loch "William"       5.300000
31   Spencer, Mrs. William Augustus (Marie Eugenie)       5.232886
205                      Strom, Miss. Telma Matilda       5.231250
813              Andersson, Miss. Ebba Iris Alfrida       5.212500
480                  Goodwin, Master. Harold Victor       5.211111

[71 rows x 2 columns]

In [ ]:
du

Which adult male passenger (age ≥ 18 and Sex is ’male’) paid the highest fare relative to their
class?
To answer the question perform following operations:
1. Add a column to the Titanic dataset, fare per class, containing the fare divided by the passenger
class i.e. Fare / Pclass.
2. Subset rows where the passenger is male (Sex is ”male”) and an adult (Age is greater than or equal
to 18), assigning this to adult males.
3. Sort adult males by descending fare per class, assigning this to adult males srt.
4. Select only the Name, Age, and fare per class columns of adult males sr and save the result
as result.
5. Look at the result.

In [ ]:
df["fare_per_class"]=df["Fare"]/df["Pclass"]
adult_males=df[(df["Sex"]=="male"),df["Age"]>=18]
adult_males_srt=adult_males.sort_values(by="fare_per_class",ascending=False)
result=adult_males_srt[["Name","Age","fare_per_class"]]
result

InvalidIndexError: (0       True
1      False
2      False
3      False
4       True
       ...
886     True
887    False
888    False
889     True
890     True
Name: Sex, Length: 891, dtype: bool, 0      True
1      True
2      True
3      True
4      True
       ...
886    True
887    True
888    True
889    True
890    True
Name: Age, Length: 891, dtype: bool)

3.3 Exploratory Data Analysis with Group-by Method Practice Exercise:
Based on the dataset Answer the following question:
What percent of the total fare revenue came from each passenger class?
To answer the question perform following operation:
1. Calculate the total Fare paid across all passengers in the Titanic dataset.
2. Subset for passengers in first class (Pclass is 1) and calculate their total fare.
3. Do the same for second class (Pclass is 2) and third class (Pclass is 3).
4. Combine the fare totals from first, second, and third classes into a list.
5. Divide the totals for each class by the overall total fare to get the proportion of fare revenue by class.

In [ ]:
total_fare=df["Fare"].sum()
total_fare

np.float64(28693.9493)

In [ ]:
fare_first=df[df["Pclass"]==1]["Fare"].sum()
fare_second=df[df["Pclass"]==2]["Fare"].sum()
fare_third=df[df["Pclass"]==3]["Fare"].sum()
fare_by_class=[fare_first,fare_second,fare_third]
fare_by_class

[np.float64(18177.4125), np.float64(3801.8417), np.float64(6714.6951)]

In [ ]:
fare_percent_class=[fare/total_fare for fare in fare_by_class]
fare_percent_class

[np.float64(0.6334928771899656),
 np.float64(0.1324962855496507),
 np.float64(0.23401083726038366)]

What percent of the total number of passengers on the Titanic belonged to each age group
(e.g., child, adult, senior)?
To answer the question perform following operation:
1. Create a new column, age group, that categorizes passengers into "child" (age < 18), "adult" (age
18{64), and "senior" (age 65 and above).
2. Calculate the total number of passengers on the Titanic.
3. Count the number of passengers in each age group.
4. Divide the count of each age group by the total number of passengers to get the proportion of passengers
in each age group.
5. Display the proportion as a percentage.

In [ ]:
def categorize_age(age):
  if age<18:
    return "child"
  elif age<65:
    return "adult"
  else:
    return "senior"
df["age_group"]=df["Age"].apply(categorize_age)
df[["Age","age_group"]].head()

    Age age_group
0  22.0     adult
1  38.0     adult
2  26.0     adult
3  35.0     adult
4  35.0     adult

In [ ]:
total_passenger=df.shape[0]
total_passenger

891

In [ ]:
age_group_counts=df["age_group"].value_counts()
age_group_counts

age_group
adult     767
child     113
senior     11
Name: count, dtype: int64

In [ ]:
age_group_percent=(age_group_counts/total_passenger)*100
age_group_percent

age_group
adult     86.083053
child     12.682379
senior     1.234568
Name: count, dtype: float64

In [ ]:
age_group_percent.round(0)

age_group
adult     86.0
child     13.0
senior     1.0
Name: count, dtype: float64